server:
  port: 8991

spring:
  application:
    name: orders
  cloud:
    consul:
      host: hyy.localhost.com
      port: 8500
      discovery:
        instance-id: ${spring.application.name}
        service-name: ${spring.application.name}
